version: "3.7"
services:
  ml_workspace_matlab:
    container_name: ml_workspace_matlab
    build: 
      context: .
      dockerfile: Dockerfile
      #args:
      #  MATLAB_VERSION: r2022b
    image:  cgvalle/ml_workspace_matlab:r2022b
    ports:
      - 9020:8080
    #volumes:
    #  - ./jupyterhub_config.py:/resources/jupyterhub_config.py
    #  - /var/run/docker.sock:/var/run/docker.sock

